// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1A8hsvGvu0kh40JHUf525g4gaN1ED7EU',
    appId: '1:261078475530:web:382117057dbf3b221050f3',
    messagingSenderId: '261078475530',
    projectId: 'moneyflow-f4ebe',
    authDomain: 'moneyflow-f4ebe.firebaseapp.com',
    storageBucket: 'moneyflow-f4ebe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1A8hsvGvu0kh40JHUf525g4gaN1ED7EU',
    appId: '1:261078475530:android:788f78f8ec45b9021050f3',
    messagingSenderId: '261078475530',
    projectId: 'moneyflow-f4ebe',
    storageBucket: 'moneyflow-f4ebe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1A8hsvGvu0kh40JHUf525g4gaN1ED7EU',
    appId: '1:261078475530:ios:YOUR_IOS_APP_ID',
    messagingSenderId: '261078475530',
    projectId: 'moneyflow-f4ebe',
    storageBucket: 'moneyflow-f4ebe.firebasestorage.app',
    iosBundleId: 'com.clopes.moneyflow',
  );
}
